apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qduc7426y-nodejs 
  janus-idp.io/tekton: qduc7426y-nodejs
  backstage.io/kubernetes-id: qduc7426y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qduc7426y-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml