apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qduc7426y-nodejs-gitops
  description: This is GitOps manifest for qduc7426y-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=qduc7426y-nodejs
    backstage.io/kubernetes-id: qduc7426y-nodejs 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: qduc7426y-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qduc7426y-nodejs
